Support Kubernetes 1.9.9
FutureSharks/tf-kops-cluster pull request #31
Opened 2018-07-18 07:50 UTC by legal90

This PR add support of k8s 1.9.9. It requires kops 1.9.*, so #30 should be merged first.
I verified it using the provided example (`example\` in the repo)

2018-07-18 08:06 UTC, v00d00 commented
I am so glad this is here, I was about to start working on the same thing :+1:

2018-07-18 08:21 UTC, legal90 commented
FYI: I'm still not sure how will it work with real payload - I just verified it with a successful result of `kops validate cluster` command.

I also noticed that `out/kubernetes.tf` output for 1.9.9 has couple more lines in comparison with 1.8.6. In particular:
```diff
--- tf-kops-cluster/example/out-1.8.6/terraform/data/aws_launch_configuration_master-eu-west-1a.masters.cluster1.euwest1.staging.kubernetes.luxe.com_user_data	2018-07-17 13:31:32 +0000
+++ tf-kops-cluster/example/out-1.9.9/terraform/data/aws_launch_configuration_master-eu-west-1a.masters.cluster1.euwest1.staging.kubernetes.luxe.com_user_data	2018-07-17 14:13:55 +0000
@@ -151,7 +151,7 @@
   - max-size=10m
   - max-file=5
   storage: overlay,aufs
-  version: 1.13.1
+  version: 17.03.2
 encryptionConfig: null
 etcdClusters:
   events:
@@ -170,6 +170,8 @@
   - PersistentVolumeLabel
   - DefaultStorageClass
   - DefaultTolerationSeconds
+  - MutatingAdmissionWebhook
+  - ValidatingAdmissionWebhook
   - NodeRestriction
   - ResourceQuota
   allowPrivileged: true
@@ -177,11 +179,12 @@
   apiServerCount: 3
   authorizationMode: RBAC
   cloudProvider: aws
+  etcdQuorumRead: false
   etcdServers:
   - http://127.0.0.1:4001
   etcdServersOverrides:
   - /events#http://127.0.0.1:4002
-  image: gcr.io/google_containers/kube-apiserver:v1.8.6
+  image: gcr.io/google_containers/kube-apiserver:v1.9.9
   insecurePort: 8080
   kubeletPreferredAddressTypes:
   - InternalIP
```
I'm pretty new to k8s, so I don't know how important these new keys are. May be it makes sence to add them to the existing templates in this module.

2018-07-18 10:08 UTC, FutureSharks commented
Hi @legal90 
You definitely need to update all the files in https://github.com/FutureSharks/tf-kops-cluster/tree/master/module/user_data with any relevant changes. For example those `kubeAPIServer` options and anything else relevant. It's a little bit of a tedious task but is very important 🙂

2018-07-18 10:09 UTC, max-rocket-internet requested changes
Please update any user-data for launch configurations

2018-11-19 12:54 UTC, legal90 commented
Uhh, sorry folks, my scope was changed and now I'm not interested in this PR anymore.
But I keep this branch available, so feel free to rebase it & change things as you want. Or just close this PR.
Thank you for your time and effort!

2018-11-19 12:57 UTC, FutureSharks commented
No worries.

2018-11-19 12:57 UTC, closed without merging